"""Aggiunti campi fornitore

Revision ID: 01749b4a93de
Revises: 5fc2097474f0
Create Date: 2026-01-12 14:23:07.819059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01749b4a93de'
down_revision = '5fc2097474f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ragione_sociale', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('partita_iva', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('telefono')
        batch_op.drop_column('partita_iva')
        batch_op.drop_column('ragione_sociale')

    with op.batch_alter_table('fornitore_prodotto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'fornitore', ['fornitore_id'], ['id'])

    op.create_table('fornitore',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ragione_sociale', sa.VARCHAR(length=200), nullable=False),
    sa.Column('partita_iva', sa.VARCHAR(length=11), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partita_iva')
    )
    # ### end Alembic commands ###
