"""Add stripe_payment_intent

Revision ID: 172bc7dacba4
Revises: 7de77c2da81d
Create Date: 2026-01-23 10:14:10.464720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172bc7dacba4'
down_revision = '7de77c2da81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.drop_column('stripe_payment_intent')

    # ### end Alembic commands ###
