"""Add stripe_session_id to ordine

Revision ID: 26cf0363292c
Revises: 310c37d8fb6f
Create Date: 2026-01-16 11:03:02.723718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26cf0363292c'
down_revision = '310c37d8fb6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.drop_column('stripe_session_id')

    # ### end Alembic commands ###
