"""Aggiunta colonna pagato

Revision ID: 310c37d8fb6f
Revises: f72ababbf03c
Create Date: 2026-01-15 10:44:14.850850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310c37d8fb6f'
down_revision = 'f72ababbf03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagato', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.drop_column('pagato')

    # ### end Alembic commands ###
