"""Aggiunta email_verificata

Revision ID: 7de77c2da81d
Revises: 4fac370afe56
Create Date: 2026-01-20 11:26:05.707613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de77c2da81d'
down_revision = '4fac370afe56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verificata', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verificata')

    # ### end Alembic commands ###
