"""Fix User

Revision ID: a006cb5bcc2b
Revises: 4db0c04dcc7f
Create Date: 2026-01-31 14:41:21.060397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a006cb5bcc2b'
down_revision = '4db0c04dcc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cognome', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('indirizzo_spedizione', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('indirizzo_fatturazione', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notifiche_ordini', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('newsletter', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('promozioni', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('promozioni')
        batch_op.drop_column('newsletter')
        batch_op.drop_column('notifiche_ordini')
        batch_op.drop_column('indirizzo_fatturazione')
        batch_op.drop_column('indirizzo_spedizione')
        batch_op.drop_column('cognome')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
