"""aggiunti campi aziendali

Revision ID: cf29ea62ca10
Revises: d9b0a8c89bd5
Create Date: 2026-01-29 11:22:26.193258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf29ea62ca10'
down_revision = 'd9b0a8c89bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('indirizzo_azienda', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefono_azienda', sa.String(length=20), nullable=True))
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_column('telefono_azienda')
        batch_op.drop_column('indirizzo_azienda')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
