"""fix fornitore_prodotto fk

Revision ID: d173a139a1f7
Revises: 01749b4a93de
Create Date: 2026-01-12 16:30:12.919392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd173a139a1f7'
down_revision = '01749b4a93de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data_ordine', sa.DateTime(), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=True),
    sa.Column('totale', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornitore_prodotto',
    sa.Column('fornitore_id', sa.Integer(), nullable=False),
    sa.Column('prodotto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornitore_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['prodotto_id'], ['prodotto.id'], ),
    sa.PrimaryKeyConstraint('fornitore_id', 'prodotto_id')
    )
    op.create_table('ordine_dettaglio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordine_id', sa.Integer(), nullable=False),
    sa.Column('prodotto_id', sa.Integer(), nullable=False),
    sa.Column('quantita', sa.Integer(), nullable=False),
    sa.Column('prezzo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ordine_id'], ['ordine.id'], ),
    sa.ForeignKeyConstraint(['prodotto_id'], ['prodotto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordine_dettaglio')
    op.drop_table('fornitore_prodotto')
    op.drop_table('ordine')
    # ### end Alembic commands ###
