"""Fix stripe_payment_intent type

Revision ID: d9b0a8c89bd5
Revises: 172bc7dacba4
Create Date: 2026-01-23 12:35:23.346176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b0a8c89bd5'
down_revision = '172bc7dacba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.alter_column('stripe_payment_intent',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.alter_column('stripe_payment_intent',
               existing_type=sa.String(length=255),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
