"""Aggiunta campi spedizione a Ordine

Revision ID: f72ababbf03c
Revises: d173a139a1f7
Create Date: 2026-01-14 12:31:44.785613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72ababbf03c'
down_revision = 'd173a139a1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cognome', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('indirizzo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('citta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cap', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('provincia', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('telefono')
        batch_op.drop_column('provincia')
        batch_op.drop_column('cap')
        batch_op.drop_column('citta')
        batch_op.drop_column('indirizzo')
        batch_op.drop_column('cognome')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
